FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy

WORKDIR /app

# базовые либы
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir fastapi "uvicorn[standard]"

COPY render.py /app/render.py

EXPOSE 8890
CMD ["uvicorn", "render:app", "--host", "0.0.0.0", "--port", "8890"]
